Solution
mate-academy/py-feed-animals pull request #293
Opened 2023-01-11 12:18 UTC by serg121192

2023-01-11 19:09 UTC, katevasilenko requested changes

2023-01-11 19:09 UTC, katevasilenko commented on app/main.py
> +                 appetite: int, is_hungry: bool = True) -> None:
```

    def __init__(
         self,
         name: str,
         appetite: int,
         is_hungry: bool = True
     ) -> None:
```
Does it look prettier?

2023-01-11 19:09 UTC, katevasilenko commented on app/main.py
> +    animals = []
Do you use it somewhere in your code? I suppose not. Remove this class attribute

2023-01-11 19:09 UTC, katevasilenko commented on app/main.py
> +        else:
Remove `else`

2023-01-11 19:09 UTC, katevasilenko commented on app/main.py
> +                 appetite: int = 3, is_hungry: bool = True) -> None:
```
    def __init__(
         self,
         name: str,
         appetite: int = 3,
         is_hungry: bool = True
     ) -> None:
```

2023-01-11 19:09 UTC, katevasilenko commented on app/main.py
> +                 appetite: int = 7, is_hungry: bool = True) -> None:
```
    def __init__(
         self,
         name: str,
         appetite: int = 7,
         is_hungry: bool = True
     ) -> None:
```

2023-01-11 19:09 UTC, katevasilenko commented on app/main.py
> +            self.is_hungry = not self.is_hungry
```suggestion
            self.is_hungry = False
```

2023-01-12 08:55 UTC, olena-hul approved these changes

2023-01-12 08:55 UTC, olena-hul commented
Good job!

2024-10-01 09:37 UTC, closed without merging