Solution
mate-academy/py-feed-animals pull request #672
Opened 2023-09-24 17:10 UTC by PyCore23

2023-09-24 17:49 UTC, Bohdan-Salamakha requested changes

2023-09-24 17:49 UTC, Bohdan-Salamakha commented on app/main.py
> +    return sum([animal.feed() for animal in animals])
```suggestion
    return sum(animal.feed() for animal in animals)
```

2023-09-24 17:49 UTC, Bohdan-Salamakha commented on app/main.py
> +def feed_animals(animals: list) -> int:
add additional typehint for list inner objects like list[YOUR_VALUE_TYPE]
for example: list that contains string elements has typehint list[str]

2023-10-18 12:27 UTC, pavlejviki requested changes

2023-10-23 10:12 UTC, viktoria-rybenchuk requested changes
fix flake8

2023-11-21 13:16 UTC, pavlejviki approved these changes
Good job!

2024-05-17 10:07 UTC, closed without merging