Solution
mate-academy/py-feed-animals pull request #857
Opened 2024-01-16 13:59 UTC by Anna728560

2024-01-16 14:26 UTC, Nick-r2c commented on app/main.py
> +        if self.is_hungry is True:
'is True' тут не потрібно бо 'self.is_hungry' це уже булеве значення, достатньо if self.is_hungry

2024-01-16 14:34 UTC, Nick-r2c commented on app/main.py
> +    for animal in passed_animals:
Зверни увагу на цей цикл, подивись що саме ти рахуєш, подивись що повертає метод feed(), 'if animal.is_hungry is True' вже десь було

2024-01-16 14:52 UTC, Nick-r2c commented on app/main.py
> +    for animal in passed_animals:
чекни що ти рахуєш в циклі, і що повертає feed(), вони чимось схожі, не впевнений шо можу більше підказати)

2024-01-17 10:14 UTC, NEkropo1 requested changes

2024-01-17 10:14 UTC, NEkropo1 commented on app/main.py
> +    passed_animals = []
Why do you need this?

2024-01-17 10:14 UTC, NEkropo1 commented on app/main.py
> +        Animal.passed_animals.append(self)
and why do you need this?)

2024-01-17 10:18 UTC, NEkropo1 requested changes
Remove unnecessary and unrequested functionality from app

2024-01-17 10:25 UTC, NEkropo1 approved these changes
Good job!

2025-05-12 21:03 UTC, closed without merging