Solution
mate-academy/py-feed-animals pull request #977
Opened 2024-03-18 09:57 UTC by Saywin

2024-03-18 14:46 UTC, Saywin commented on app/main.py
> +        if self.is_hungry:
done

2024-03-18 16:24 UTC, vsmutok requested changes

2024-03-18 16:24 UTC, vsmutok commented on app/main.py
> +    return sum([animal.feed() for animal in animals])
```suggestion
    return sum(animal.feed() for animal in animals)
```
no need to create list in this case

2024-03-18 16:30 UTC, Saywin commented on app/main.py
> +    return sum([animal.feed() for animal in animals])
done

2024-03-18 16:54 UTC, vsmutok approved these changes
Great!

2024-03-19 06:15 UTC, Saywin commented
Thanks for checking

2025-07-01 11:49 UTC, closed without merging